version: 2
updates:
  # github-actions
  - directory: "/"
    package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
    groups:
      all-github-actions:
        patterns: ["*"]
    commit-message:
      prefix: "dependabot"
      include: scope
    labels:
      - "kind/cleanup"
      - "area/dependency"

  # Go - root directory
  - directory: "/"
    package-ecosystem: "gomod"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
    commit-message:
      prefix: "dependabot"
      include: scope
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "github.com/prometheus/*"
        update-types: [
            "version-update:semver-major",
            "version-update:semver-minor",
          ] # Consume only patch updates.
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
      - dependency-name: "sigs.k8s.io/cloud-provider-azure"
      # Ignore subpackage releases of opentelemetry-go; just watch go.opentelemetry.io/otel.
      - dependency-name: "go.opentelemetry.io/contrib/*"
      - dependency-name: "go.opentelemetry.io/otel/exporters/*"
      - dependency-name: "go.opentelemetry.io/otel/metric"
      - dependency-name: "go.opentelemetry.io/otel/sdk*"
      - dependency-name: "go.opentelemetry.io/otel/trace"
    labels:
      - "kind/cleanup"
      - "area/dependency"

  # Go - hack/tools directory
  - directory: "/hack/tools"
    package-ecosystem: "gomod"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      time: "09:00"
    commit-message:
      prefix: "dependabot"
      include: scope
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"
      # Ignore subpackage releases of opentelemetry-go; just watch go.opentelemetry.io/otel.
      - dependency-name: "go.opentelemetry.io/contrib/*"
      - dependency-name: "go.opentelemetry.io/otel/exporters/*"
      - dependency-name: "go.opentelemetry.io/otel/metric"
      - dependency-name: "go.opentelemetry.io/otel/sdk*"
      - dependency-name: "go.opentelemetry.io/otel/trace"
    labels:
      - "kind/cleanup"
      - "area/dependency"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "dependabot"
      include: scope
    ignore:
      - dependency-name: "golang"
    labels:
      - "kind/cleanup"
      - "area/dependency"
