run:
    go: "1.18"
    timeout: 10m
    tests: false
    allow-parallel-runners: true
    skip-dirs:
      - "./*/mock"

linters-settings:
  funlen:
    lines: 110
    statements: 60
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"
  cyclop:
    max-complexity: 15
    skip-tests: true
  gosec:
    exclude-generated: true
  lll:
    line-length: 120
  misspell:
    locale: GB
  goimports:
    local-prefixes: github.com/weaveworks-liquidmetal/cluster-api-provider-microvm
  govet:
    check-shadowing: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
    - err
    - wg

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
  - text: "shadow: declaration of \"err\" shadows declaration"
    linters:
    - govet
  - text: "should not use dot imports|don't use an underscore in package name"
    linters:
    - golint
  - text: "local replacement are not allowed: github.com/weaveworks-liquidmetal/cluster-api-provider-microvm/"
    linters:
    - gomoddirectives
  - text: "github.com/weaveworks-liquidmetal/"
    linters:
    - wrapcheck
  - source: "https://"
    linters:
    - lll
  - source: "\\+kubebuilder"
    linters:
    - lll
  - path: _test\.go
    linters:
    - goerr113
    - gocyclo
    - errcheck
    - gosec
    - dupl
    - funlen
    - scopelint
    - testpackage
  - path: version/
    linters:
    - gochecknoglobals
  - path: api/
    linters:
    - gochecknoglobals
  - path: internal/command/
    linters:
    - exhaustivestruct
    - lll
    - wrapcheck
  - source: "// .* #\\d+"
    linters:
    - godox

linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - golint
  - interfacer
  - maligned
  - scopelint
  - tagliatelle
  - wrapcheck
