//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2021 Weaveworks or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MPL-2.0
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&MicrovmMachine{}, func(obj interface{}) { SetObjectDefaults_MicrovmMachine(obj.(*MicrovmMachine)) })
	scheme.AddTypeDefaultingFunc(&MicrovmMachineTemplate{}, func(obj interface{}) { SetObjectDefaults_MicrovmMachineTemplate(obj.(*MicrovmMachineTemplate)) })
	return nil
}

func SetObjectDefaults_MicrovmMachine(in *MicrovmMachine) {
	for i := range in.Spec.MicrovmSpec.NetworkInterfaces {
		a := &in.Spec.MicrovmSpec.NetworkInterfaces[i]
		SetDefaults_NetworkInterface(a)
	}
}

func SetObjectDefaults_MicrovmMachineTemplate(in *MicrovmMachineTemplate) {
	for i := range in.Spec.Template.Spec.MicrovmSpec.NetworkInterfaces {
		a := &in.Spec.Template.Spec.MicrovmSpec.NetworkInterfaces[i]
		SetDefaults_NetworkInterface(a)
	}
}
