name: release

on:
  push:
    tags:
    - "v*.*.*"

env:
  TAG: ${{ github.ref_name }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0
    - name: Docker login
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image
      run: make docker-build TAG=${{ env.TAG }}
    - name: Push docker image
      run: make docker-push TAG=${{ env.TAG }}
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0
    - name: Build release manifests
      run: |
        TAG=${{ env.TAG }} make manifest-modification
        kustomize build config/default/ > infrastructure-components.yaml
    - name: Release
      uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
      with:
        prerelease: false
        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        discussion_category_name: Announcements
        name: ${{ env.TAG }}
        files: |
          templates/cluster-template.yaml
          templates/cluster-template-cilium.yaml
          templates/cluster-template-flannel.yaml
          metadata.yaml
          infrastructure-components.yaml
